### ISSUE TITLE
可否提供一份 SIGHAN2008 数据集，或者，我可以到哪获取它

### ISSUE THREAD

**Issue by YingZhuY** [acphile/MCCWS#2]

**Comment by ghost** [comment]
我也在找，还没找到下载的链接，如果你可以找到给我共享一下好嘛。

这个是我找到的一些信息，说数据集是非公开的：
- https://github.com/hankcs/multi-criteria-cws
- https://github.com/hankcs/multi-criteria-cws/issues/14

这是当年会议的地址，里面公布的链接已经失效了：
- https://www.aclweb.org/mirror/ijcnlp08/sighan6/papersubmission.htm

这是第二届和第三届会议的数据集地址：
- http://sighan.cs.uchicago.edu/bakeoff2005/
- http://sighan.cs.uchicago.edu/bakeoff2006/download.html （这个需要身份验证，下不到）

**Comment by YingZhuY** [comment]
Hello, and your e-mail?
